

List<Map<String, dynamic>> achievementMapList = [
  {'No': '10', 'title': '新たな習慣のはじまり','body':'新たな習慣のスタートです！今日は始められたことを高く評価して、すぐヤメちゃっても良いと思います。','num':1,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No': '20', 'title': '2歩目が大事','body':'映画でもなんでも２で終わっちゃうことがあると思うので、２回目って大事だと思います。','num':2,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No': '30', 'title': '3代目！','body':'王様や将軍は３代目が重要とよく言われます。習慣においても大事な回数です。','num':3,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No': '40', 'title': '3代目！継続を守る','body':'王様や将軍は３代目が重要とよく言われます。習慣においても大事な回数です。とりあえず毎日続けることが大事！毎日ポチポチ習慣を開始していきましょう！','num':0,'combo_num':3,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'50','title':'3代目！目標時間を守る','body':'王様や将軍は３代目が重要とよく言われます。習慣においても大事な回数です。３回も目標時間内に開始できている！忙しければ忙しい人ほどこれができるのはすごい！','num':0,'combo_num':0,'due_num':3,'combodue_num':0,'restart':0},
  {'No':'60','title':'3代目！継続し、目標時間も守る','body':'王様や将軍は３代目が重要とよく言われます。習慣においても大事な回数です。３回も継続して目標時間も守る！素晴らしい！','num':0,'combo_num':0,'due_num':0,'combodue_num':3,'restart':0},
  {'No':'70','title':'良い調子！','body':'良い調子です！とりあえず開始することだけに集中しましょう！','num':5,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'80','title':'良い調子！継続を守る','body':'良い調子です！とにかく続ける！とにかく続ける！','num':0,'combo_num':5,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'90','title':'W・Ａ・ピーターソンの名言','body':'『変化するには、古い習慣を新しい習慣に置きかえねばならない。』W・Ａ・ピーターソンはアメリカの作家、コラムニストです。雑誌で長年掲載したことで知られる人物です。','num':0,'combo_num':0,'due_num':5,'combodue_num':0,'restart':0},
  {'No':'100','title':'アリストテレス の名言','body':'人は物事を繰り返す存在である。したがって、優秀さとは行動によって得られるものではない。習慣になっていなければならないのだ。','num':0,'combo_num':0,'due_num':0,'combodue_num':5,'restart':0},
  {'No':'110','title':'1 週間分達成！','body':'今日で7回目！１週間分です！段々慣れてきたかもしれませんね！','num':7,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'120','title':'勝利とは習慣なのだ','body':'ヴィンス・ロンバルディというアメリカフットボールのコーチの名言のようです。その後にも続き「残念ながら、敗北も同じ。」だそうです。勝負師の名言。深い。。。','num':0,'combo_num':7,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'130','title':'吉田松陰の名言','body':'『人間たる者、自分への約束を破る者が最もくだらぬ。』だそうです。厳しいな松陰先生。','num':0,'combo_num':0,'due_num':7,'combodue_num':0,'restart':0},
  {'No':'140','title':'孔子の名言','body':'人の本性は皆ほとんど同じである。違いが生じるのはそれぞれの習慣によってである。','num':0,'combo_num':0,'due_num':0,'combodue_num':7,'restart':0},
  {'No':'150','title':'10回達成！','body':'10回分習慣を実施することができました！というかここまでアプリ使ってくれてありがとうございます！','num':10,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'160','title':'プロゲーマー「ウメハラ」さんのエピソード','body':'プロゲーマーのウメハラさんは365日中、363日（大晦日と元日以外）は毎日のようにゲーセンに通ってたそうです。大会で崖っぷちになっても、『俺よりゲーセン行ってるやつはいない！』という自負があり最後まであきらめず戦うことができるそうです。','num':0,'combo_num':10,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'170','title':'声優「林原めぐみ」さんの歌詞','body':'曲『raging waves』より抜粋『いきなり強いわけじゃない。いきなりできるわけじゃない。繰り返していく日々からつくりあげていくの自分を』','num':0,'combo_num':0,'due_num':10,'combodue_num':0,'restart':0},
  {'No':'180','title':'ウイリアム・ジェームズの名言','body':'『習慣が変われば人格が変わる。人格が変われば運命が変わる。』アメリカの哲学者、心理学者である、ウィリアム・ジェームズの名言です。','num':0,'combo_num':0,'due_num':0,'combodue_num':10,'restart':0},
  {'No':'190','title':'20回達成！','body':'20回、習慣達成！そろそろ何か手ごたえを感じているかもしれません。','num':20,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'200','title':'レフ・トルストイの名言','body':'『私は毎日書かなければならない。それは成果をあげるためではなく、習慣を失わないためだ。』ロシアの文豪と言われるトルストイの言葉です。','num':0,'combo_num':20,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'210','title':'イチローさんの言葉','body':'『小さいことを積み重ねるのが、とんでもないところへ行くただひとつの道だと思っています』','num':0,'combo_num':0,'due_num':20,'combodue_num':0,'restart':0},
  {'No':'220','title':'アリストテレスの言葉','body':'『人は習慣によってつくられる。優れた結果は一時的な行動ではなく、習慣から生まれる』古代ギリシャの哲学者 アリストテレスの言葉です。数千年も前から伝わっている言葉。説得力ありすぎです。','num':0,'combo_num':0,'due_num':0,'combodue_num':20,'restart':0},
  {'No':'230','title':'科学的に習慣が定着する日(21日)','body':'科学的に21日継続すると習慣が定着すると言われています。これ以降は習慣をやめようとしても、抵抗を感じるようになると言われています。実際どうでしょうか？','num':0,'combo_num':21,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'240','title':'１カ月分！','body':'これで１か月分の習慣を始められたことになります！ボタンを押すだけかもしれないけど、非常に大事な習慣が身についていると思います。','num':30,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'250','title':'継続人','body':'３０連続で習慣を実施できる人・・・人はそれを『継続人』と呼ぶ！','num':0,'combo_num':30,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'260','title':'時間を管理できる人','body':'３０回も目標時間内に習慣を始められる人、時間を自在に管理できる人、時を操れるといっても過言ではありません。いや。過言か。。','num':0,'combo_num':0,'due_num':30,'combodue_num':0,'restart':0},
  {'No':'270','title':'千日の稽古を鍛とし万日の稽古を練とする！','body':'剣豪。宮本武蔵の言葉です。１０００日は約３年１００００日は約２７年。まだまだかもしれませんが、ここまで来ているのであればもしかしたら。。。','num':0,'combo_num':0,'due_num':0,'combodue_num':30,'restart':0},
  {'No':'280','title':'甲斐性のある人','body':'「甲斐性がある」ということは辞典的な意味だと「物事をやり抜こうとする気力や根性が十分にある人」のことを指すそうです。','num':40,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'290','title':'小事が大事を生む','body':'プロ野球選手「野村克也」さんの言葉です。ホームラン王の王貞治選手の次にホームランを打った人で、さらに監督しても名将と言われた人です。','num':0,'combo_num':40,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'300','title':'薫習（くんじゅう）','body':'「薫習（くんじゅう）」とは香が物にその香りを移していつまでも残るように、みずからの行為が心に習慣となって残ることを意味します。','num':0,'combo_num':0,'due_num':40,'combodue_num':0,'restart':0},
  {'No':'310','title':'もう何か変わっているはず！','body':'ここまでくると、もう何か変わっているはず！何か成果として出ているかも、そうでなくても心境は変わっているはず！','num':0,'combo_num':0,'due_num':0,'combodue_num':40,'restart':0},
  {'No':'320','title':'習慣50回達成！という武器','body':'「50回。習慣を開始できた」これが武器になります。','num':50,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'330','title':'習慣は第二の天性である。','body':'マルクス・トゥッリウス・キケロ。共和政ローマ末期の政治家、弁護士、文筆家、哲学者の言葉です。紀元前の偉人の言葉です。もう習慣という武器があなたの手に！','num':0,'combo_num':50,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'340','title':'時間を作れる人','body':'目標時間内に始められる人。それは時間を作れる人です。もう何やってもうまくいくはず！','num':0,'combo_num':0,'due_num':50,'combodue_num':0,'restart':0},
  {'No':'350','title':'工夫の天才','body':'そもそも50日連続で、目標時間内に習慣を開始するには。精神論ではできません。それを実行できる工夫をしているはず。だからはあなたは『工夫の天才』かもしれません。','num':0,'combo_num':0,'due_num':0,'combodue_num':50,'restart':0},
  {'No':'360','title':'60回達成！この称号が意味するもの。','body':'もしここまでくるに何回も失敗を重ねてきた人は何かが身についているはず。自信を持って良いと思います。','num':60,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'370','title':'『習慣』という武器','body':'もうあなたは『習慣』という武器を手に入れています。おそらく何をやるにしても困らないかと思います。','num':0,'combo_num':60,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'380','title':'時間管理のプロ','body':'目標時間内に始められるのであれば、もう時間管理のプロ！誰かに教えられるレベルです！','num':0,'combo_num':0,'due_num':60,'combodue_num':0,'restart':0},
  {'No':'390','title':'アプリ卒業','body':'こんなにできるのであれば、もうこのアプリに頼らなくても十分。何するにしても習慣化する癖がつけられる人になっていると思います！','num':0,'combo_num':0,'due_num':0,'combodue_num':60,'restart':0},
  {'No':'400','title':'淡々とする奥義','body':'「淡々とする」言葉にすればあっけないですが、こと習慣にしては奥義です。','num':70,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'410','title':'『継続』という切り札','body':'もうあなたには『継続』という手札があります。これは人生すべてを変えるカードです。','num':0,'combo_num':70,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'420','title':'時の支配者！','body':'目標時間内に70回も習慣を始められた、まさにあなたは時を支配しているのかもしれません。','num':0,'combo_num':0,'due_num':70,'combodue_num':0,'restart':0},
  {'No':'430','title':'称号とかで喜ばない境地','body':'多分これ以上続けている人は称号とかで喜ばない人なのかもしれません。淡々と出来でいるはずです。つーかネタ切れですｗ','num':0,'combo_num':0,'due_num':0,'combodue_num':70,'restart':0},
  {'No':'440','title':'80回！習慣マスター','body':'80回もやり続けているあなたは習慣マスターです！','num':80,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'450','title':'習慣継続マスター','body':'習慣継続マスター！流石！','num':0,'combo_num':80,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'460','title':'習慣期日マスター','body':'習慣期日マスター！','num':0,'combo_num':0,'due_num':80,'combodue_num':0,'restart':0},
  {'No':'470','title':'習慣継続期日マスター','body':'習慣継続期日マスター！すごすぎです。予定とか突然入ったりしないんですか？','num':0,'combo_num':0,'due_num':0,'combodue_num':80,'restart':0},
  {'No':'480','title':'90回！習慣王！','body':'90回！習慣王！あと10回で・・・・','num':90,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'490','title':'習慣継続王','body':'習慣継続王！ここまで継続するのはすごい！','num':0,'combo_num':90,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'500','title':'習慣期日王','body':'習慣期日王！ここまで時間を守れるのはすごい。天性のものかもしれません。','num':0,'combo_num':0,'due_num':90,'combodue_num':0,'restart':0},
  {'No':'510','title':'習慣継続期日王','body':'習慣継続期日王！とにかくヤベーっす！もうこんなに自分をコントロールできるんだったら思うがままじゃないですか？','num':0,'combo_num':0,'due_num':0,'combodue_num':90,'restart':0},
  {'No':'520','title':'習慣神','body':'100回！習慣神です！','num':100,'combo_num':0,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'530','title':'習慣継続神','body':'習慣継続神、ここまでできるのはスゴイ！','num':0,'combo_num':100,'due_num':0,'combodue_num':0,'restart':0},
  {'No':'540','title':'習慣期日神','body':'時間を操る神でしょう！時間との付き合い方が神がかっております。','num':0,'combo_num':0,'due_num':100,'combodue_num':0,'restart':0},
  {'No':'550','title':'習慣継続期日神','body':'もう世界はあなたの思うまま！？','num':0,'combo_num':0,'due_num':0,'combodue_num':100,'restart':0},
  {'No':'560','title':'習慣復活１回','body':'一回途切れても再開！素晴らしいです。','num':0,'combo_num':0,'due_num':0,'combodue_num':0,'restart':1},
  {'No':'570','title':'諦めない心','body':'途切れても再スタート！','num':0,'combo_num':0,'due_num':0,'combodue_num':0,'restart':3},
  {'No':'580','title':'達磨','body':'７転び８起きの精神！','num':0,'combo_num':0,'due_num':0,'combodue_num':0,'restart':8},
  {'No':'590','title':'不屈の闘志','body':'やめてもやめても立ち上がる！まさに不屈の闘志！','num':0,'combo_num':0,'due_num':0,'combodue_num':0,'restart':10},
  {'No':'600','title':'習慣ゾンビ','body':'習慣やめてもやめても立ち上がる。そんなあなたは習慣ゾンビ！不名誉ですかね。。。','num':0,'combo_num':0,'due_num':0,'combodue_num':0,'restart':15},
  {'No':'610','title':'不死鳥','body':'だいたい、途切れたらやる気が無くなるのが人間と言うもの。それすらも超越するあなたは不死鳥です！','num':0,'combo_num':0,'due_num':0,'combodue_num':0,'restart':30}

];


